language: node
env:
  - NODE_VERSION=0.10
install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - npm install -g npm@^2.0.0
  - node --version
  - npm --version
  - git --version
  - svn --version | head -n 1
  - npm install -g gulp
  - npm install

os:
  - osx
  - linux

script:
  - gulp travis
